
package consultaresolucionfacturacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 */
@WebService(name = "resolucionFacturacionPortName", targetNamespace = "http://www.dian.gov.co/servicios/facturaelectronica/ConsultaResolucionFacturacion")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ResolucionFacturacionPortName {


    /**
     * @param consultaResolucionesFacturacionPeticion
     * @return returns co.gov.dian.servicios.facturaelectronica.consultaresolucionfacturacion.ResolucionesFacturacion
     */
    @WebMethod(operationName = "ConsultaResolucionesFacturacion")
    @WebResult(name = "ConsultaResolucionesFacturacionRespuesta", targetNamespace = "http://www.dian.gov.co/servicios/facturaelectronica/ConsultaResolucionFacturacion", partName = "ConsultaResolucionesFacturacionRespuesta")
    public ResolucionesFacturacion consultaResolucionesFacturacion(
            @WebParam(name = "ConsultaResolucionesFacturacionPeticion", targetNamespace = "http://www.dian.gov.co/servicios/facturaelectronica/ConsultaResolucionFacturacion", partName = "ConsultaResolucionesFacturacionPeticion")
                    ConsultaResoluciones consultaResolucionesFacturacionPeticion);

}
