
package consultadocumentos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 */
@WebService(name = "consultaDocumentoPortName", targetNamespace = "http://www.dian.gov.co/servicios/facturaelectronica/ConsultaDocumentos")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ConsultaDocumentoPortName {


    /**
     * @param consultaResultadoValidacionDocumentosPeticion
     * @return returns co.gov.dian.servicios.facturaelectronica.consultadocumentos.DocumentosRecibidos
     */
    @WebMethod(operationName = "ConsultaResultadoValidacionDocumentos")
    @WebResult(name = "ConsultaResultadoValidacionDocumentosRespuesta", targetNamespace = "http://www.dian.gov.co/servicios/facturaelectronica/ConsultaDocumentos", partName = "ConsultaResultadoValidacionDocumentosRespuesta")
    public DocumentosRecibidos consultaResultadoValidacionDocumentos(
            @WebParam(name = "ConsultaResultadoValidacionDocumentosPeticion", targetNamespace = "http://www.dian.gov.co/servicios/facturaelectronica/ConsultaDocumentos", partName = "ConsultaResultadoValidacionDocumentosPeticion")
                    EnvioConsultaDocumento consultaResultadoValidacionDocumentosPeticion);

}
